[project]
name = "htm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.1.0",
    "plotly>=5.22.0",
    "pytest>=9.0.2",
    "scalene>=2.0.1",
    "streamlit>=1.39.0",
]
